# Generated by Django 3.1.1 on 2020-10-13 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback',
            new_name='ContactForm',
        ),
    ]
