# Generated by Django 3.1.1 on 2020-10-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20201013_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='name',
            field=models.CharField(help_text='Name of the sender', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='subject',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
