# Generated by Django 3.1.1 on 2020-10-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20201013_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
